### ISSUE TITLE
Defect: Critical - .pdf files are missing; 404 page displayed

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#10]
When clicking on the URL's that should open .pdf files - 404 page is displayed

**Steps to reproduce:**
1. Go to for example to **Trucks -> VNR Electric -> Specifications**
2. Scroll down to Resources
3. Click on Download Brochure button from the first icon
4. Notice that .pdf file does not open and 404 page is displayed

**Expected result**
.pdf file for the Download Brochure should correctly open

**Actual result**
.pdf file does not open and 404 page is displayed

**Note:** Issue occurs on both French Canada and English Canada and this issue will be updated with examples of pages and sections where this occurs

01. **Trucks -> VNR Electric -> Specifications**

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/9e3f86cf-7234-4a3b-82db-d357e7782451)

**Comment by rrusher** [comment]
I found and resolve several of these.

**Comment by Andrei-Boiangiu** [comment]
2. **Trucks -> VNL -> Features**

<img width="1901" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/016c4754-ff31-4591-a95c-ed3106a3837f">

**Comment by Andrei-Boiangiu** [comment]
3. **Trucks -> VNX -> Features**
only of French Canada site

<img width="1876" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/0a098ac9-ef13-4250-9cae-fc6fd7f4a683">

**Comment by rrusher** [comment]
**Paint brochure is fine for both languages:**
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnl/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnl/features

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnx/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnx/features

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vah/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vah/features

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed for the sections in the above comment

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/i-shift-transmission/i-shift-crawler-gears
