### ISSUE TITLE
Defect: Major - VNR Truck page - URL link is missing on Smooth Operator section

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#11]
On the VNR Truck page - the Smooth Operator section is missing the URL link

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnr and scroll down to the OPERATEUR LISSE section
2. Notice the missing link on Smooth Operator
3. Repeat same steps for https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/trucks/vnr
4. Notice that there is a link present but it takes you to the same page you are on

**Expected result**
Smooth Operator should include the link to the respective page

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/727ed26f-f9b6-49a5-a92d-12696b2f7a39)

**Actual result**
Smooth Operator does not include the link (French Canada) or it includes a link but for the same page you are on (English Canada)

**Comment by Andrei-Boiangiu** [comment]
same issue present for the Read More section on the VNL Truck page

https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnl

<img width="1912" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/6a3b4185-2e46-475c-bdf1-c2a54b0aa59e">

**Comment by rrusher** [comment]
Resolved.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed for the examples above 
with the exception of
 the Read More link on https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnl from the comment above
takes the user to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-en/news-and-stories/volvo-trucks-magazine/savings-compounded
which is a Page not found / Invalid URL

**Comment by rrusher** [comment]
**Both links worked for me:**
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/volvo-trucks-magazine/savings-compounded
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/news-and-stories/volvo-trucks-magazine/savings-compounded
**coming from:**
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnl

**Comment by Andrei-Boiangiu** [comment]
closed as fixed
