### ISSUE TITLE
Defect: Major - An URL text is incorrectly displayed on Trucks VNL page

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#12]
On the VNL Truck page - an incorrect URL is displayed on one of the News Item blocks

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnl and scroll down to the News Items blocks
2. Notice the URL text incorrectly displayed

**Expected result**
The incorrectly displayed URL text should not be there

**Actual result**
There is an URL text incorrectly displayed on one of the News Item blocks

<img width="1912" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/9f14ad33-8bfe-464b-8297-fd5ed0f242b1">

**Comment by rrusher** [comment]
Content issue fixed.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
