### ISSUE TITLE
Defect: Major: fr-ca : Footer has additional links , additional translated text i.e. not same as that of existing site

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#15]
Steps:
1. Navigate to https://www.volvotrucks.ca/fr-ca/parts-and-services/parts/genuine/
2. Validate the footer 

Expected vs Actual:
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/d7ae8663-0394-4bed-b0ef-dfd0a7c8c8a3)

**Comment by rrusher** [comment]
Since this site is a copy of the US site (the new site), we should confirm with Joe what the footer should have.

**Comment by rrusher** [comment]
Joe confirmed that all sites should have the SDS Information.
https://adobe-dx-support.slack.com/archives/C04G7PQ5QG3/p1684780774616199

**Comment by girishdigrajkar** [comment]
Thanks @rrusher for confirmation closing the defect.
