### ISSUE TITLE
Defect: Critical - Powertrain page - Several blocks and sections are missing from the Powertrain page

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#19]
On the Volvo Powertrain page, several blocks / sections are missing. on both French Canada and English Canada sites

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/powertrain 
2. Go to https://www.volvotrucks.ca/fr-ca/trucks/#VOLVO%20D11%20ENGINE
3. Notice that first page contains much less content and blocks than the live page

4. Repeat the same steps for English Canada sites

**Expected result**
Powetrain page needs to have the blocks present on the Live page

**Actual result**
Powertrain page for both fr-ca and en-ca has several blocks missing from its content

**Comment by rrusher** [comment]
Link 2 is the wrong page. It takes you to the Trucks page: https://www.volvotrucks.ca/fr-ca/trucks/
The new sites take you to the Powertrain page: https://www.volvotrucks.us/trucks/powertrain/
