### ISSUE TITLE
Defect: Major - VHD Truck: Interior - An incorrect character displayed in one of the blocks

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#22]
On the **VHD Truck -> Interior** there is an incorrect character displayed in one of the blocks

<img width="1303" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/3d348cad-f6a9-480c-85aa-67363a2e37bf">

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vhd/interior
2. Scroll down and notice the incorrectly displayed character from the image above

**Comment by rrusher** [comment]
Republished. Resolved.
