### ISSUE TITLE
Defect: Major - VAH Truck: Specification page - The images on the Specifications table are incorrectly compressed

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#23]
On the VAH Truck -> Specifications page, the images on the Specifications table are too compressed

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/fr-ca/trucks/vah/specifications/ and scroll down to the Specifications table
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vah/specifications and scroll down to the Specifications table
3. Notice the images of the trucks from the table

**Expected result**
Images on the Specifications table should not be compressed

**Actual result**
Images on the Specifications table of the VAH Truck: Specifications page are incorrectly compressed

<img width="1841" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/9a6e3f74-467e-46ab-9fae-999af6261803">

**Comment by rrusher** [comment]
This issue is also on Volvotrucks.us.
It will be resolve by a CSS change.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
