### ISSUE TITLE
Magazine articles - some of them aren't appearing

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-ca#25]
**URLs**
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/news-and-stories/volvo-trucks-magazine
Test URL
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/news-and-stories/volvo-trucks-magazine/denney-story

**Steps to reproduce**
Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/news-and-stories/volvo-trucks-magazine
Clicks on a magazine article link
Wait for the article to load

**Expected behavior**
The magazine article loads as well as the balance of the site content

**Actual behavior**
A blank page appears

<img width="865" alt="Blank magazine page" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/126615590/8f3700e9-c923-472e-ab88-874fe778c40a">
<img width="736" alt="Magazine Landing page" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/126615590/eb470865-086b-4c98-89f6-b6ddef72ecd0">

Live magazine article
<img width="845" alt="English Magazine article on live ca site" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/126615590/68e37498-0584-4b23-a37f-d35c6dd5c8b5">

**Comment by rrusher** [comment]
The language was missing from the URL on the Volvo Trucks Magazine page. All links on the page were reviewed and adjusted as needed.
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/news-and-stories/volvo-trucks-magazine
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/news-and-stories/volvo-trucks-magazine

**Comment by KJohnsn** [comment]
I checked the links and they work as expected. I am able to see the Magazine articles after clicking the links for both English and French.
