### ISSUE TITLE
Defect: Major - Powertrain: D13 - D13 Engine Brochure button is missing from block component

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#26]
On the Powertrain: D13 page - the D13 Engine Brochure button is missing from the first block component

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/fr-ca/trucks/powertrain/d13/ 
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/d13
3. Notice the button missing from the first block

**Expected result**
D13 Brochure button should be present and correctly open the brochure .pdf

**Actual result**
D13 Brochure button is missing
<img width="1901" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/ea60afbf-99b7-4e5d-8002-d0f723f414f4">

**Comment by rrusher** [comment]
Brochure is not on https://www.volvotrucks.us/trucks/powertrain/d13/
I found the PDF and uploaded it to [vg-volvotrucks-us > media > vtna > files > shared > powertrain](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-volvotrucks-us/media/vtna/files/shared/[powertrain](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-volvotrucks-us/media/vtna/files/shared/powertrain?csf=1&web=1&e=TPLEzO)?csf=1&web=1&e=TPLEzO), but was not able to publish it.

File is revised4147-101-volvo-d13-engine-brochure-low-res.pdf

**Comment by rrusher** [comment]
Brochure is published. This issue is resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/d13
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/powertrain/d13

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
