### ISSUE TITLE
Defect: Minor - Powertrain: Transmission I-Shift page - Section of text missing from Image Text block

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#27]
On the Powertrain: Transmission I-Shift page, there is portion of text missing from the Automation Upgraded Image Text block

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/fr-ca/trucks/powertrain/i-shift-transmission/ and scroll down to the AUTOMATISATION AMÉLIORÉE.. section
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/powertrain/i-shift-transmission and scroll down to the AUTOMATISATION AMÉLIORÉE.. section
3. Notice the missing portion of text

**Expected result**
The portion of text should be included in the block

**Actual result**
This section of text is missing from the Image Text block

<img width="1901" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/a1372934-48d6-4f4a-a3bb-c58e2c643efb">

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/trucks/powertrain/i-shift-transmission
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/powertrain/i-shift-transmission

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
