### ISSUE TITLE
Bug: Minor :  The text from VOLVO GENUINE ENGINE PARTS is not as expected & noticed additional 'View Brochure' Link 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#28]
**Steps:**
1.  Navigate to  https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/parts-and-services/parts/genuine/engine
2. Validate the text for  VOLVO GENUINE ENGINE PARTS section
3. Validate the links

Expected : 
VOLVO GENUINE ENGINE PARTS
Volvo Genuine Parts are designed for ultimate reliability, durability, and performance. They are quality assured and fulfill Volvo’s specifications and stringent requirements. Volvo Genuine offers a complete assortment of new engine parts to service all the systems within your engine. Our complete offering of Genuine cooling, exhaust, lubrication, and filtration parts are specifically crafted to keep your engine running and your truck moving forward.

Actual:
Volvo Genuine Engine Parts
Volvo Genuine offers a complete assortment of new engine parts to service all of the systems within your engine. Genuine cooling, exhaust, lubrication, and filtration parts are specifically crafted to keep your engine running and your truck moving forward.

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/e6a4ea76-9032-4173-8374-a76be6c28827)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/609cf740-c2b5-466e-9770-ca8f407d04a6)

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/parts-and-services/parts/genuine/engine
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/parts/genuine/engine

**Comment by Andrei-Boiangiu** [comment]
can be closed as fixed ( I dont have the option to Close ticket )
