### ISSUE TITLE
Defect: Major - FR-CA site - Trucks: Applications - The Applications subpage is different on the French Canada site

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#29]
On the French-Canada VolvoTrucks site, the Applications page has "Flatbed" subpage instead of "LTL-Moins qu'un camion"

**Steps to reproduce:**
1. Open https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/applications
2. Open https://www.volvotrucks.ca/fr-ca/trucks/applications/
3. Notice the different second subpage in the header, first one has "Flatbed" and second one has "LTL-Moins qu'un camion"
4. Click on the respective subpages
5. Notice that they are different pages

**Expected result**
French Canada helix site should have "LTL-Moins qu'un camion" on Applications page

**Actual result**
French Canada helix site has "Flatbed" as subpage on Applications page (like the English Canada site)

<img width="1735" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/b8f228d6-a6e1-4d83-b6a8-cae2d888022d">

**Comment by rrusher** [comment]
Since https://www.volvotrucks.ca/en-ca/trucks/applications/ has "Flatbed" and https://www.volvotrucks.ca/fr-ca/trucks/applications/ has "LTL - Moins qu'un camion", I picked one (flatbed) and made them both the same since it is better to be consistent across languages.
