### ISSUE TITLE
Defect: Minimal - About Volvo: Our Difference - Text on the Hero component and title of Main Component is switched

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#30]
On the About Volvo: Our Difference page - the text on the Hero Component and the title of the Main Component is switched between them

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/en-ca/our-difference/
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference
3. Notice the text on the Hero component and the title of the Main component below on most pages - Text from the subtitle of the Main component is on the Hero component and the text on the Hero component is added as the title of the Main component below
4. Same applies for both French Canada and English Canada

<img width="1887" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/69694cf4-2d02-4165-ae6a-f70e0cd7cd2a">

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/our-difference
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference
