### ISSUE TITLE
Bug: Major:  'Search the Network' button opens a new window unlike expected to be open in same window

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#31]
Steps:
1. Go to  https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/genuine/overhaul-program
2. Click on 'Search the Network' button

Expected vs Actual:
The new page opens in new window unlike expected.

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/0a340dd5-83cf-4590-b4c8-00cf4b6469a3)

**Comment by rrusher** [comment]
The site copies what is done for the US site: https://www.volvotrucks.us/find-a-dealer/

**Comment by Andrei-Boiangiu** [comment]
can be closed as fixed
