### ISSUE TITLE
Defect: Minor - About Volvo: Our Difference page - The Top-Ten component block is missing the the hover effect and font styling

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#32]
On the About Volvo: Our Difference page - the Top Ten component with the three big images with text over are missing the hover effect and the font styling / position is different

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/en-ca/our-difference/
2. Scroll down to the top ten component block and notice the mouse cursor hover effect over the images
3. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference
4. Notice that the hover effect is missing and the font styling and position of the text over the images is different

**Expected result**
Images on the block should have the mouse cursor hover effect and font styling and position should be different

<img width="1908" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/af322a8b-6181-490d-98ef-d89a3474765f">

**Actual result**
Images on the block do not have the mouse cursor hover effect and the font styling and positioning is different

<img width="1908" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/9ab02cc4-93ce-4dbe-8c3d-7a015ebac7a8">

**Comment by rrusher** [comment]
Joe told us not to migrate top10 and use an equivalent standard block.

**Comment by Andrei-Boiangiu** [comment]
issue closed based on above comment
