### ISSUE TITLE
Defect: Critical - Missing video button overlay and missing videos (part 2) #7

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#33]
**About Volvo -> Our Difference -> Uptime and Connectivity** has missing video button overlay, missing video link additionally missing magazine article link on the third image

**Steps to reproduce:**

1. Go to https://www.volvotrucks.ca/fr-ca/our-difference/uptime-and-connectivity/ and notice the video button overlay , the video links and links on the third image
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/uptime-and-connectivity
3. Notice that the video button overlay and links are missing

**Expected result**
Video button overlay, video links and magazine link on the third image should be present

**Actual result**
Video button overlay, video links and magazine link are missing

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/9ea73e60-0696-41af-b7e0-99fc6ed0fc43)

**Comment by Andrei-Boiangiu** [comment]
02. **Our Difference -> Safety -> Active Driver Assist**

<img width="1895" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/27ee270f-baa3-4bd8-87c2-b5e656105616">

**Comment by rrusher** [comment]
Asked Joe how he would like us to handle this issue: https://adobe-dx-support.slack.com/archives/C04G7PQ5QG3/p1685027396711039
