### ISSUE TITLE
Bug: Major: subtab is different and when clicked it results in error page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#34]
Steps:
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/parts/all-makes
2. Validate the sub tabs

Expected vs Actual:
'PartsASSIST' link is resulting in error page

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/d44b015c-5735-4165-b4a4-07d52598c179)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/4eff69a7-4d0a-4f5c-8e75-eb3a7465c3c5)

**Comment by rrusher** [comment]
Resolved:
PartsASIST is not on https://www.volvotrucks.ca/en-ca/parts-and-services/parts/
And it is broken on https://www.volvotrucks.ca/fr-ca/parts-and-services/parts/. It has a copy of "All-Makes" in the navigation.

I have copied the PartsASIST off the US site.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 
 can be closed as fixed ( I do not have the option to Close it )
