### ISSUE TITLE
Bug: Major: The 'Learn more' link is not displayed and casing of heading is incorrect

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#35]
Steps:
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/services/uptime-service-solutions
2. Validate the 'Uptime & Connectivity' section heading
3. Validate the 'Learn More' link

Expected vs Actual:
1. 'Uptime & Connectivity' section heading casing is title case unlike capital
2. 'Learn More' link under 'Uptime & Connectivity'  section is not displayed

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/956463fc-70f4-49c2-a2aa-4491b41ff4ea)

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/parts-and-services/services/uptime-service-solutions
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/services/uptime-service-solutions

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 

can be closed as fixed ( I do not have the option to close it )
