### ISSUE TITLE
Bug: Major: Check marks are missing from 'Diagnostic Tools Comparison' section

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#36]
Steps:
1. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/services/uptime-service-solutions/diagnostic-tools
2. Validate the Diagnostic Tools Comparison section
3. Validate the DIAGNOSTIC TOOLS BREAKDOWN section heading

Expected vs Actual:
Diagnostic Tools Comparison section does not have any check marks as expected 
DIAGNOSTIC TOOLS BREAKDOWN section casing is title case unlike Capital casing

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/7c059938-dc8c-4b97-a223-55edfb3d8f62)

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/parts-and-services/services/uptime-service-solutions/diagnostic-tools
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/services/uptime-service-solutions/diagnostic-tools

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
