### ISSUE TITLE
Bug: Major: Video missing from 'Volvo Trucks — Maximize Uptime & Productivity with ASIST' & other page sections

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#37]
Steps:
Case 1:
1. Navigate to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/service-management-platform-asist
2. Validate the video below 'Vos véhicules à portée de main' section

Case 2:
1. Navigate to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/remote-diagnostics
2. Validate the video below 'MAXIMISEZ LES RÉPARATIONS UPTIME ET EXPEDITE' section

Case 3:
1. Navigate to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/dealer-network
2. Validate the video below 'Peu importe où, nous sommes là pour votre entreprise' section

**Expected vs Actual:**
Case 1: No video is displayed under 'Vos véhicules à portée de main' section

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/c586e343-98b4-445e-8804-090aece93edf)

Case 2: No video is displayed under 'MAXIMISEZ LES RÉPARATIONS UPTIME ET EXPEDITE' section
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/46254677-95fa-47b7-b0ec-27a1ddec4797)

Case3: No video is displayed under 'Peu importe où, nous sommes là pour votre entreprise' section
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/dd63d79a-6f9a-4f37-9742-15c9d1e2c2b5)

**Comment by rrusher** [comment]
Resolved:
http://localhost:3000/fr-ca/our-difference/uptime-and-connectivity/service-management-platform-asist

https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/our-difference/uptime-and-connectivity/remote-diagnostics
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/remote-diagnostics

https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/our-difference/uptime-and-connectivity/dealer-network
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/dealer-network

**Comment by Andrei-Boiangiu** [comment]
On case 1
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/service-management-platform-asist

and on case 3
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/dealer-network

the videos do not work

<img width="1315" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/a5bcec0d-8365-4537-94ce-4d371123ade1">

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference/uptime-and-connectivity/service-management-platform-asist
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/uptime-and-connectivity/service-management-platform-asist

**Comment by girishdigrajkar** [comment]
Case 1 & Case2 works now however, Case3 i.e. on below URL pages video does not work, @rrusher : Please check.. Thanks.. 
 https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/our-difference/uptime-and-connectivity/dealer-network
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/dealer-network

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/our-difference/uptime-and-connectivity/dealer-network
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/dealer-network

Content issue: The mp4 file name did use the proper case.

**Comment by girishdigrajkar** [comment]
Confirmed as fixed
