### ISSUE TITLE
Bug: Major: The google plus social media icon is not displayed and 'Related Content' section has different styling

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#38]
Steps:
1. Navigate to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/news-and-stories/volvo-trucks-magazine/the-connected-future
2.  Validate the google plus icon
3. validate the 'Related Content' Section

Expected vs Actual:
The google plus icon is not displayed & Related content has different date format.

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/8c3ccf5a-183a-4700-976e-198f788d63ff)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/330ee792-990b-43aa-9216-62561369491a)

**Comment by rrusher** [comment]
Google+ was deprecated a few years ago, so you should not see that social link anywhere.
