### ISSUE TITLE
Defect: page missing when clicking Volvo Logo in any page, this action should bring user back to home page

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-ca#4]
On the dealer locator page when the user clicks on the Volvo Logo in the top left hand corner which should take the user back to the home page, seeing the error in the screen shot below. Happening on both the FR and EN Canada sites. 
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/e0168698-f290-43cc-b3f9-d3bb9aae506e)

**Comment by dkuntze** [comment]
fixed. Example:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/powertrain/d13
