### ISSUE TITLE
Defect: Major - Uptime and connectivity: Fleet Management - Choose Volvo blocks are arranged vertically instead of horizontally

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#41]
On https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/fleet-management, the blocks on the bottom of the page are arranged vertically instead of horizontally

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/fr-ca/our-difference/uptime-and-connectivity/fleet-management/ and scroll down to the Choose Volvo section
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/fleet-management and scroll down to the Choose Volvo section
3. Notice that the blocks are arranged vertically

**Expected result**
The blocks from the Choose Volvo section should be aligned horizontally

**Actual result**
The blocks from the Choose Volvo section are arranged vertically

<img width="1895" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/2b49c7f5-aa96-4b39-910a-f3a7e195fc6f">

**Comment by rrusher** [comment]
Resolved: content issue, block was not applied.
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/uptime-and-connectivity/fleet-management
