### ISSUE TITLE
Defect: Major - Missing images

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#42]
On Active Driver Assist there is a missing image from the page

01. **Our Difference -> Safety -> Active Driver Assist**

<img width="1895" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/1a1295e5-3ed5-4abd-83bb-80fa4d221db1">

**NOTE:** this ticket is to be updated if there are further examples of missing images

**Comment by rrusher** [comment]
Asked Joe: https://adobe-dx-support.slack.com/archives/C04G7PQ5QG3/p1685027396711039
