### ISSUE TITLE
Defect: Major - Hero Image - Our Difference: Safety: Active Driver Assist - Text on the Hero Image is placed outside the Hero Image

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#43]
On the Our Difference -> Safety -> Active Driver Assist page, the Text is displayed outside the Hero Image

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/fr-ca/our-difference/safety/active-driver-assist/ and see the Hero Image blocks
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/our-difference/safety/active-driver-assist and see the Hero Image blocks
3. Notice that the text is outside the Hero Image blocks

**Expected result**
Text should be on the Hero Images

**Actual result**
Text is displayed outside of the Hero Images (see left half of the screenshot)

<img width="1895" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/98d11b21-5749-4a8b-a879-89a2d109e1ef">

**Comment by rrusher** [comment]
Resolved: rebuilt using the same block as other language.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
