### ISSUE TITLE
Add New Icon on Volvo Blue Service Contract Page

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-ca#44]
We have a new icon attached that should replace the truck icon for Adaptive Maintenance in both sections 

![Image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/7d1230bd-2e1d-42d6-b299-ab5fc01b20a9)
![Image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/f48fe35a-be50-43f1-bfb9-005ee3464f0e)

https://www.volvotrucks.us/purchasing-a-truck/service-contracts

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
