### ISSUE TITLE
Dealer locator issues

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-volvotrucks-ca#51]
This issue tackles the dealer locator issues present in [THIS](https://github.com/hlxsites/vg-volvotrucks-us/issues/521) issue + the positioning of the google logo and information on the bottom of the map.

**Comment by BeckyMedlin** [comment]
@SantiagoHomps-NC I assume this is for Volvo Trucks stream. Please change if that's incorrect. Thank you!

**Comment by girishdigrajkar** [comment]
Validated and able to get correct results **except for the positioning of the google logo position as it is overlapped due to dealer list**   Please investigate:

**Comment by shirin27** [comment]
From @BeckyMedlin on slack: It should be implemented in the same way that Volvo Trucks US works today.
From @Joesturbo on slack: On the dealer locator we agreed with the ability to hide the locator slider and correction to show the right hand text at the bottom it is closed. No need to block the release.

**Comment by girishdigrajkar** [comment]
As per above confirmation from Joe,  able to get the correct results and hence, marking this ticket to done status.
