### ISSUE TITLE
Content issues observed : Volvotrucks Canada site (en-ca)

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#53]
While testing ticket #[50](https://github.com/hlxsites/vg-volvotrucks-ca/issues/50) below content issues observed

**Steps:**
Navigate to https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/  and validate :

**Issues Observed:**
1. - [x] When clicked on Find a dealer on home page  it navigate to https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/find-a-dealer/    thus results in no page found .....   '/' after find a dealer in URL is the issue 

2.  - [x] 'Electromobility' section on homepage has no background video set
Functional issue:  Clicking on Explore within  Electromobility section navigates to https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/innovation/electromobility/ which does not shows page ;   Extra '/'  in URL is the issue

3.   - [ ] Footer :  >Resources > Safety recalls  link is not displayed ; sequence of Privacy  | Cookies is interchanged in footer links

4.   - [x]   Sub nav missing in en-ca

5. - [x]  homepage >  Our truck lineup >  VNL > Explore ->.  page not displayed    :  '/' issue;  Build yours CTA does not load page

6. - [x] homepage > Our truck lineup > VNR > Build yours CTA does not load page

7.  - [x] homepage > Our truck lineup > VNX  >   Page is not displayed   ;  '/' Issue

8. - [x] homepage > Our truck lineup > VHD >  Page is not displayed  ; '/' Issue

9. - [x] homepage > Our truck lineup > VAH > Page is not displayed ; '/' Issue

10. - [ ] Homepage :  'Stories from the road' section :  date format(2022-05-25)  is different than that of us site (e.g. 1/30/2024)

11.  - [x] https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/all-new-vnl/#safety      >>    Ecall > Video is not authored

12. - [ ] ~https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/all-new-vnl/#resources   >>. Download Brochures functionality results in 404 error page~  
13. https://www.volvotrucks.ca/en-ca/all-new-vnl/Files/volvo-vnl-aerodynamics-features-brochure.pdf. results in 404 error.

14.  - [x] https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/all-new-vnl/#resources     >>    See all locations does not load any page   >  '/' issue

15.  - [x] https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/purchasing-a-truck/financing/      >>.  no subnav displayed

16. - [ ] ~https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/all-new-vnl/#resources  >>    'Explore Service Contracts ->'    page is not authored~  
https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/purchasing-a-truck/service-contracts  Click on 'Find a Dealer' it shows page couldn't be dispalyed.

17. - [x] Footer :  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/about-volvo/our-story    Click on 'Read more >'  under OUR HISTORY >  page is not displayed >> '/' issue

18. - [ ] Footer : Click on 'Contact us' link  :  differences in sub nav noted , please see :
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/37396ea3-9365-4fa2-86d0-e0f592f5eb0a)

19.  - [ ] no sub nav on below pages :
~https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/services/resources/~
https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/material-safety-data-sheets/ 

20. - [x] https://www.volvotrucks.us/parts-and-services/parts/material-safety-data-sheets/     SDS PDF files are resulting in 404 error page

21. - [ ] https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/material-safety-data-sheets/    Find a dealer is not authored

22. - [ ] Site title has &amp :  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/services/resources/

**Comment by girishdigrajkar** [comment]
Validated and issues related to redirects are no more visible;  Status for all reported sub points has been validated.

**Comment by BeckyMedlin** [comment]
@Kannan-CM Needs to review and then publish the CA site.
