### ISSUE TITLE
Content issues observed : Volvotrucks Canada site (fr-ca) 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-ca#54]
Canada :  fr-ca site 
**Steps:**
Navigate to  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/     & validate

**Observations:**
    

- 1. [ ] When clicked on Find a dealer on home page  it navigate tohttps://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/find-a-dealer/   is not displayed correctly

- [ ] 2. CONTENT ISSUE :  'Electromobility' section on homepage has no background video set

Functional issue:  Clicking on Explore within  Electromobility section navigates to https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/innovation/electromobility/  is not authored 

- [x] 3.  Sub nav missing in fr-ca : https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/about-volvo/our-story/

- [ ] 4.  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/  >> 		[Camions](https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/)     >>   Volvo VNX & Volvo VHD models are not available 

- [x] 5.  https://www.volvotrucks.ca/fr-ca/truck-builder  page is not displayed

- [ ] 6.  homepage >  Our truck lineup >  VNL > Explore ->.  Takes user to live site which should be same environment

- [ ] 7.  homepage > Our truck lineup > ALL-NEW VNL > EXPLORE > Takes user to live site which should be same 

‘Build Yours’ CTA when clicked shows page not found

- [x] 8.  homepage > Our truck lineup > VNR > Build yours CTA does not load page

- [x] 9.  homepage > Our truck lineup > VNX  >   Page is not displayed   ;  '/' Issue

- [x] 10. homepage > Our truck lineup > VHD >  Page is not displayed  ; '/' Issue

- [x] 11. homepage > Our truck lineup > VAH > Page is not displayed ; '/' Issue

- [ ] 12. Homepage :  'Stories from the road' section :  date format(2022-03-27)  is different than that of us site (e.g. 1/30/2024)

- [ ] 13: https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/ >>  Under ‘Our truck lineup’  click on  ALL-NEW VNL  >  Click on ‘EXPLORE ->’ CTA ,  it takes to live site i.e. https://www.volvotrucks.us/trucks/all-new-vnl/  unlike to the branch url  

- [x] 14:  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/purchasing-a-truck/financing/      >>.  no subnav displayed

- [x] 15:  Footer : Click on 'Contact us' link  :    No sub nav displayed

- [x] 16: no sub nav on below pages :

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/parts-and-services/services/resources/

[https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/parts-and-services/parts/material-safety-data-sheets/](https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/material-safety-data-sheets/)

- [ ] 17:  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/parts-and-services/parts/material-safety-data-sheets/.  SDS PDF files are resulting in 404 error page

- [ ] 18: https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/material-safety-data-sheets/    Find a dealer is not authored
&  Site title has &amp :  

- [x] 19. https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/parts-and-services/services/resources/  Click on  Camions  > Powertrain >  All links results in page not found except [I-Shift Transmission](https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/powertrain/i-shift-transmission/) &  [Emissions](https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/emissions/)

- [ ] 20. Below links are not configured :
https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/purchasing-a-truck/service-contracts/

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/parts-and-services/services/body-builder-support/

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/parts-and-services/fleets/volvo-connect

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/innovation/supertruck2/

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/innovation/electromobility/

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/links/megamenu/careers/

https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/purchasing-a-truck/volvo-certified/

- [ ] 21. https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/purchasing-a-truck/inventory-search/  no content authored 

- [x] 22.  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/volvo-trucks-magazine/    &  https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/press-releases/       page has incorrect content as can see Bulletpoints ; 

- [ ] 23. https://develop--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/login/  results in page not found

**Comment by girishdigrajkar** [comment]
Validated and marked completed issues post redirect fix from Syb...

**Comment by BeckyMedlin** [comment]
@Kannan-CM Zoe will create a Teams ticket for this work. She'll close this ticket when it's ready.

**Comment by ZoeBeykirch** [comment]
Closing Github ticket, as this has moved into [Teams tickets ](https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:60544d25c46a4290847f6b4dcd8e4eec@thread.skype_p_p1AaLYbsHkCzGFXovIZmRZYACbV8_h_1632160719313?tenantId=f25493ae-1c98-41d7-8a33-0be75f5fe603&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2Fd6Zab5OfKkCSTliV9NWzh5YAM4gG%22%2C%22channelId%22%3A%2219%3A60544d25c46a4290847f6b4dcd8e4eec%40thread.skype%22%7D)for CMS to resolve:
