### ISSUE TITLE
Bug: Login Page Showing 404 Error, Content Editors Cannot Publish New Page

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-ca#57]
### Issue Type

Bug

### Summary

404 Error for EN and FR Login sites 

### Priority

Blocker

### Description

There are 404 errors for the following log in pages: https://www.volvotrucks.ca/en-ca/login/ and https://www.volvotrucks.ca/fr-ca/login/

As content editors, we cannot publish any new page to correct this error. On Zoe's side when testing, the preview attempt generates an error message. On Joe's side he is able to see the following preview link: https://rd-test--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/login/

When both content editors try to publish a new page, it still does not seem to publish the page as the 404 error remains. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

System wide issue across all devices and browsers. 

### Steps to Reproduce

1. Navigate to: https://www.volvotrucks.ca/en-ca/login/ and https://www.volvotrucks.ca/fr-ca/login/
2. Observe the 404 error. 
3. Open the Sharepoint environment, https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2FVolvoGroup%2Fvg%2Dvolvotrucks%2Dca%2Fen%2Dca%2Flogin&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95
4. We have tried re-naming the documents, copying and creating new word documents to publish, and still the issue persists. 

### Expected Results

Log in page should mirror the USA site to have the same content and copy as: https://www.volvotrucks.us/login/

### Actual Results

shows a 404 error

### Attachment

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/0f59c693-db56-4dc4-844d-13c8772c6079)
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/11d41798-57f9-4f8c-9553-2ef038be8c48)

**Comment by jonatan-lledo-netcentric** [comment]
Both pages are live now. the `Bulk operation failed` error could happen sometimes but it's a matter of connection issues more than an EDS bug. I published this page and check the other login page and both are live now
<img width="1791" alt="Screenshot 2024-03-21 at 09 09 08" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/117984204/2b4ded93-f017-4acf-abe1-2a848a982fc9">

**Comment by jonatan-lledo-netcentric** [comment]
A potential fix if this happens again is the following:
1- in a browser tab with the Sharepoint page opened, open dev tools and go to the `application` tab then In the application list go to storage and click on `Clear site data`.
2- after refreshing the page it will ask again to log in
3- it should be up and running again after login again

**Comment by ZoeBeykirch** [comment]
@jonatan-lledo-netcentric Looks like your suggestion worked!! Thanks again for your quick help and support here 🥇
