### ISSUE TITLE
Defect: Major - All TEXT ALIGNMENT differences ( same Text Alignment issues as were present on Volvo Trucks US )

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#6]
see the following defect that was opened for Volvo Trucks US

[Defect: Major - All TEXT ALIGNMENT differences #215](https://github.com/hlxsites/vg-volvotrucks-us/issues/215)

All the same Text Alignment differences on the same pages that were present on the above mentioned are also present on the French Canada website: 
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnr 

and on the English Canada website:
https://main--vg-volvotrucks-ca--hlxsites.hlx.live/en-ca/trucks/vnr

**Comment by ZoeBeykirch** [comment]
Additionally, the Driving Progress Volvo Truck Lineup needs to be centered on the home pages

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/a81244bb-676e-4f36-a113-afaccd2960d4)
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/bff61c75-b049-4ffc-a5ff-9514850a6a3b)

**Comment by ZoeBeykirch** [comment]
On the VNR Electric page:
1. The "Future Is Here" sub-headline needs to be moved to be in the hero image, above the "The Volvo VNR Electric" headline. 
2. The "Vous emmener plus loin avec l'électrique" needs to be centered with font adjusted
3. The 3 image icons size need to be enlarged. 

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/64dd00d4-12ec-4624-9453-b85ee5aa2455)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125895595/304e6dd4-7599-458b-8730-6e777b6baa61)

**Comment by rrusher** [comment]
Both issues @ZoeBeykirch reported have been resolved.

**Comment by girishdigrajkar** [comment]
Text Alignment issue noted :
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/genuine/overhaul-program

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/b738aa11-19b0-4f34-9e94-f71c1c639908)

**Comment by girishdigrajkar** [comment]
Text alignment issue observed on:    https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/remanufactured/overhaul-program

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/1b33f729-e907-4858-b276-5d31bb2110ae)

**Comment by girishdigrajkar** [comment]
Text alignment issue observed on: https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/remanufactured/overhaul-program

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/b23542d7-7c77-451a-8344-62ae48e163a6)

**Comment by girishdigrajkar** [comment]
Text alignment issue observed on page : https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/parts-and-services/services/uptime-service-solutions/certified-uptime-dealers

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/125972657/1fda75b7-5071-4fe0-8980-908c6bedd15f)
