### ISSUE TITLE
Bug - Press Releases are not loading in Volvo CA (en-ca) homepage 

### ISSUE THREAD

**Issue by Varunvolvo** [hlxsites/vg-volvotrucks-ca#63]
### Issue Type

Bug

### Summary

News news post 2021 are not appearing in main page 

### Priority

Blocker

### Description

The Press releases main page is not showing the recently published articles. The issues in the Press Release Main page are - 

1. The first block is showing up a disclaimer text which is not a news article. Whixh should basically not showup.
2. The last article that is shown is - (2020-11-10). 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1, Navigate to Volvo Trucks CA website and under News and Section click Press Releases. 
2. Preview the page and the issue can be viewed

### Expected Results

Recent articles should be displayed. 

### Actual Results

The last article is of (2020-11-10). 

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/139381543/89679b30-976a-467f-bce6-b6dac0503eba)

### Attachment

![1](https://github.com/hlxsites/vg-volvotrucks-ca/assets/139381543/ac139c8d-eada-4296-a662-0d888c862c5a)

**Comment by amglebihan** [comment]
@Varunvolvo @Kannan-CM It appears to be a content/configuration issue. Firstly, the disclaimer page was mistakenly added to the [press-releases.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B823E2D2A-B425-42D0-9803-84A74691C04C%7D&file=press-releases.xlsx&action=default&mobileredirect=true&wdsle=0) file (as seen in the last entry of the raw_index tab and the first entry of the helix_default tab), where it shouldn't be. Additionally, it seems the order of the press releases is determined by the helix_default tab. On [volvotrucks.us](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BB2E80EC7-9B79-40CE-BD61-A4441AF45942%7D&file=press-releases.xlsx&action=default&mobileredirect=true&wdsle=0), the press releases are listed by date (newest to oldest), but this is not the case for [volvotrucks.ca](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B823E2D2A-B425-42D0-9803-84A74691C04C%7D&file=press-releases.xlsx&action=default&mobileredirect=true&wdsle=0). What I don't know is who typically maintains those files.

**Comment by Kannan-CM** [comment]
HI @amglebihan ,
The "**press-releases.xlsx**" file get auto updated. We don't manage it.

**Comment by amglebihan** [comment]
@Varunvolvo, does the [disclaimer.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B81A286F3-A7FA-4BA3-9B3B-D15F3E3F16CB%7D&file=disclaimer.docx&action=default&mobileredirect=true&wdsle=0) page serve any purpose? It is being indexed and showing up in press releases. If it’s not necessary, or was created for testing purpose, we should unpublish and remove it. I also don't see any specific logic that handles the display of press releases in chronological order, starting with the newest. They are currently displayed in the order they appear in the helix_default tab in this [file](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B823E2D2A-B425-42D0-9803-84A74691C04C%7D&file=press-releases.xlsx&action=default&mobileredirect=true&wdsle=0).

**Comment by Kannan-CM** [comment]
Hi @amglebihan ,

Disclaimer is used on all the Press releases at the bottom of the page:

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/126496977/cc5f1f7f-9b40-4b30-966d-84bb238e2805)

**Comment by amglebihan** [comment]
@Kannan-CM We should then prevent it from being indexed, as it will appear in the press releases [JSON](https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/press-releases.json).

**Comment by amglebihan** [comment]
I removed the disclaimer page from the [press-releases.xlsx](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B823E2D2A-B425-42D0-9803-84A74691C04C%7D&file=press-releases.xlsx&action=default&mobileredirect=true&wdsle=0) file. It doesn't show up anymore in the JSON on the [preview link](https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/press-releases.json), but it still does in the [JSON](https://www.volvotrucks.ca/en-ca/press-releases.json?offset=0&limit=255) on the live site. It might be a cache issue.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence issue could be closed :

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/65abbf2f-4a2b-4c47-94f2-131639039d37">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/93e262b4-45fb-4d57-9d18-f25b28c1ea7a">

@amglebihan : Please proceed closure of this bug.

cc: @Kannan-CM
