### ISSUE TITLE
[Volvotrucks.ca] The site can not be accessed

### ISSUE THREAD

**Issue by silviulungu** [hlxsites/vg-volvotrucks-ca#66]
### Issue Type

Defect

### Summary

The constants file is missing and the site can't be loaded.

### Priority

High

### Description

Unable to acces the site https://main--volvotrucks-ca--volvogroup.aem.live/fr-ca/ because of the missing constants file.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Chrome

### Steps to Reproduce

1. Access this link https://main--volvotrucks-ca--volvogroup.aem.live/fr-ca/

### Expected Results

The site could be opened and working properly.

### Actual Results

The site is not loading and the page is blank.
<img width="1724" alt="Screenshot 2024-10-04 at 11 18 58" src="https://github.com/user-attachments/assets/12a0d27b-69c6-4338-8b89-75ce455f6650">

**Comment by alexiscoelho** [comment]
No fix is necessary here. Moving this to test just to validate all is good

**Comment by alexiscoelho** [comment]
No fix is necessary here. Closing
