### ISSUE TITLE
Defect: Critical - Missing video button overlay and missing videos 

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#7]
The video button overlay is missing from images and clicking will not open the video

**Steps to reproduce:**
1. Open https://www.volvotrucks.ca/fr-ca/trucks/vnr-electric/ and scoll down to the images with video button overlay
2. Open https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnr-electric and scroll down to the images with video button overlay
3. Notice that the video button overlay is not present and the video cannot be played

4. Repeat the same for https://www.volvotrucks.ca/fr-ca/trucks/vnr-electric/  and https://main--vg-volvotrucks-ca--hlxsites.hlx.live/fr-ca/trucks/vnr-electric

**Expected result**
Video buttons should be present and video should be correctly played when clicking

**Actual result**
Video button overlay is missing and the video cannot be played

**NOTE:** this issue will be updated with screenshots and examples from other pages where this issue occurs

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/e16d50e8-9156-461d-9a81-084339ae6644)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/884a1d00-2be2-4dc9-b81b-a5405072f946)

02. **Trucks -> VNR Electric -> Specifications**

<img width="955" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/c55b9012-f2f7-4663-84ae-13089cad9e39">

**Comment by rrusher** [comment]
I searched for all videos and made corrections in both languages.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed for the above examples

**Comment by Andrei-Boiangiu** [comment]
Reopening this issue for the following case on **About Volvo -> Our Difference -> Uptime and Connectivity** that has missing video button overlay, missing video link additionally missing magazine article link on the third image

**Steps to reproduce:**
1. Go to https://www.volvotrucks.ca/fr-ca/our-difference/uptime-and-connectivity/ and notice the video button overlay , the video links and links on the third image
2. Go to https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/uptime-and-connectivity
3. Notice that the video button overlay and links are missing

**Expected result**
Video button overlay, video links and magazine link on the third image should be present

**Actual result**
Video button overlay, video links and magazine link are missing

<img width="1893" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/c9650bd9-2958-4c47-8fdc-85299c56e6ec">

**Comment by Andrei-Boiangiu** [comment]
as I am not able to reopen this ticket at the moment
 
 a separate ticket was created for the case in the comment above -> #33
