### ISSUE TITLE
Defect: Critical - YouTube videos are missing

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#8]
The embedded YouTube videos are missing. on **both** French Canada and English Canada
 examples of pages where this occurs include 
 
 01. **Trucks -> VNR -> Exterior**
 
 
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/d45c9fde-3fca-421d-9a92-514b3130dc3f)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/f7d8b8b8-7463-40c9-993a-48dcbb64bff7)

 
 02. **Trucks -> VNR -> Interior**
 
 
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/b89111b8-2c72-4fd2-8181-51e3f2293b0e)

 
 03. **Trucks -> VNR -> Features**
 
![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/d6fe2aa6-7d43-4595-8aeb-fe676a2f8d2b)

**NOTE:** Issue to be updated with further examples of pages where this occurs

**Comment by Andrei-Boiangiu** [comment]
4. **Trucks -> VNL -> Exterior**

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/10b5863d-26a0-4fbc-9aee-ff8b5cd662ea)

**Comment by rrusher** [comment]
VNR Features video is not available
<img width="739" alt="Screenshot 2023-05-19 at 12 36 57 AM" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/6796243/16b4caa1-bd03-45ee-8fa6-2be2af802464">

**Comment by rrusher** [comment]
I resolved the others.

**Comment by Andrei-Boiangiu** [comment]
6. **Trucks -> VNL -> Interior** (second video)

![image](https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/176bbb61-7fec-4271-b024-8cd258531b32)

**Comment by Andrei-Boiangiu** [comment]
7. **Trucks -> VNL -> Features**

<img width="1901" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/10bc8d37-39e5-47ff-9a94-557ea7a69185">

**Comment by Andrei-Boiangiu** [comment]
8. **Trucks -> VNX -> Features**

<img width="1876" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/39b16cba-afb2-4c7b-a9dd-cc36b8f7eeca">

**Comment by rrusher** [comment]
**Missing MP4:**   Requested MP4 from customer via [Slack](https://adobe-dx-support.slack.com/archives/C04G7PQ5QG3/p1684776701716699).
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnl/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnl/features

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/d13tc
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/powertrain/d13tc

**Resolved:**
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnl/interior
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnl/interior

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnx/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnx/features

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnx/exterior
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnx/exterior

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnx/interior
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnx/interior

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed for the ones marked as Resolved in the above comment

with the exception of 
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/d13tc
which seems to have different components and no youtube video on the page

**Comment by Andrei-Boiangiu** [comment]
12. **Trucks -> Powertrain -> I-Shift Transmission -> I-Shift Crawler Gears**

<img width="1895" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/9366a9fa-f464-4330-b385-c3b9a623bd44">

**Comment by rrusher** [comment]
> confirmed as fixed for the ones marked as Resolved in the above comment
> 
> with the exception of https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/d13tc which seems to have different components and no youtube video on the page

The en-ca pages will be duplicates of the US site. The fr-ca pages were imported from the CA fr-ca site, some of which are just different.
These differences should be handled by the customer.

**Comment by rrusher** [comment]
> https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/powertrain/d13tc

This matches the US site.

**Comment by rrusher** [comment]
**Known missing MP4s:**
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/news-and-stories/volvo-trucks-magazine/investing-for-the-future
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/volvo-trucks-magazine/investing-for-the-future

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/news-and-stories/volvo-trucks-magazine/one-sweet-ride
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/volvo-trucks-magazine/one-sweet-ride

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference/safety/active-driver-assist
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/safety/active-driver-assist

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference/uptime-and-connectivity/volvo-action-service
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/uptime-and-connectivity/volvo-action-service

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnl/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnl/features

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnr/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnr/features

http://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/innovation/supertruck
http://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/innovation/supertruck

**Comment by rrusher** [comment]
**Known missing MP4s:**
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/news-and-stories/volvo-trucks-magazine/investing-for-the-future
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/volvo-trucks-magazine/investing-for-the-future
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/investing-for-the-future/

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/news-and-stories/volvo-trucks-magazine/one-sweet-ride
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/news-and-stories/volvo-trucks-magazine/one-sweet-ride
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/one-sweet-ride/

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference/safety/active-driver-assist
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/safety/active-driver-assist
https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/safety/active-driver-assist/

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/our-difference/uptime-and-connectivity/volvo-action-service
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/our-difference/uptime-and-connectivity/volvo-action-service
https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/volvo-action-service/

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnl/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnl/features
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnl/features/

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnr/features
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnr/features
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/features/

http://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/innovation/supertruck
http://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/innovation/supertruck
https://main--vg-volvotrucks-us--hlxsites.hlx.page/innovation/supertruck/
