### ISSUE TITLE
Defect: Critical - Subnavigation block is missing when navigating subpages

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-ca#9]
When selecting a Truck and navigating to a subpage (for example **VNR -> Exterior**) the Subnavigation bar dissapears and user needs to go back to the initial truck page in order to navigate to a different subpage

**Steps to reproduce:**
1. Go to **Trucks -> VNR** for example; - the subnavigation bar is present
2. Go to **Trucks -> VNR -> Exterior** 
3. Notice that the Subnavigation bar is not displayed anymore

4. Repeat the same process for other sections that have a subnavigation bar; for example Services -> Parts -> Genuine -> Engline

**Expected result**
Subnavigation bar should be displayed on any subpage of the respective section

**Actual result**
Subnavigation bar dissapears when navigating to a subpage and user has to go back in order to navigate to a different subpage

<img width="955" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-ca/assets/127409602/405c895a-af22-4346-b2e1-d92556209eed">

**Comment by rrusher** [comment]
Resolved
Here are some sample pages:
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/parts-and-services/parts/genuine/engine
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/vnr/exterior
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/vnr/interior

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed

**Comment by rrusher** [comment]
Resolved:
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/emissions
https://main--vg-volvotrucks-ca--hlxsites.hlx.page/fr-ca/trucks/emissions

https://main--vg-volvotrucks-ca--hlxsites.hlx.page/en-ca/trucks/applications

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
